### ISSUE TITLE
Callback URL gives Bad Request

### ISSUE THREAD

**Issue by joost-heijden** [fbsamples/graph-api-webhooks-samples#20]
I'll try to insert the Heroku app for my Facebook Messenger, but i get a Bad Request when i add the url to the callback URL.

https://facebook-messenger-raved.herokuapp.com/facebook

Someone can help me?

**Comment by revaxl** [comment]
If I'm not wrong if shows a bad request because the request can't process the facebook GET request.
why is it happening? because the code is a bit old and few stuff have changed.
if you try to console log your req.param you won't find anything there.
the solution I found and worked (at least for me) is to change this part:
`app.get(['/facebook', '/instagram'], function(req, res) {   
  if (
    req.param('hub.mode') == 'subscribe' &&
    req.param('hub.verify_token') == token
  ) {
    res.send(req.param('hub.challenge'));
  } else {
    res.sendStatus(400);
  }
});`
to this
`app.get('/webhook', function(req, res) {   
  if (
    req.query['hub.mode'] == 'subscribe' &&
    req.query['hub.verify_token'] == token
  ) {
    res.send(req.query['hub.challenge']);
    console.log('ok');
  } else {
    res.sendStatus(400);
  }
});`

**Comment by Kilenaitor** [comment]
Probably getting bad request because the heroku environment variables were not configured properly. 

More info is in the first part of the docs here: https://developers.facebook.com/docs/graph-api/webhooks/sample-apps

Specifically bullet-point 4: 

> In your Heroku app's settings, set up two config vars: APP_SECRET and TOKEN. Assign (paste) your App Secret to the APP_SECRET config var, and assign any string to TOKEN. We will include this string in any verification requests when you configure the Webhooks product in the App Dashboard (the app will validate the request on its own).

You can do this on Heroku website by modifying the settings for your app, or do it with the heroku CLI with 

```
heroku config:set APP_SECRET=<your-facebook-app-secret> -a <your-heroku-app-name>
```
```
heroku config:set TOKEN=<token-used-in-subscription-dialog> -a <your-heroku-app-name>
```
